### ISSUE TITLE
Default `ALLOWED_HOSTS = ['*']`

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/ansible-tiaas2#11]
Hey, is there a reason why the playbook sets `ALLOWED_HOSTS = ['*']`?

Would it not be safer to do:
```
ALLOWED_HOSTS = [
    'localhost',
    '{{ inventory_hostname }}',
]
```

I'm updating our tiaas role for deploying/testing the "new" tiaas2 so I will PR this soon, so if the answer is "yes", it'll come through in my PR.

**Comment by hexylena** [comment]
Yes, that would be a better default. I think those two will handle the proxied case as well, I think that looks good.
