### ISSUE TITLE
Redundant copying of static assets

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/ansible-tiaas2#13]
@hexylena 
I am wondering if we could just reference the galaxy style sheet directly rather than copying and re-serving from tiaas?
Maybe I am missing some logic here.

https://github.com/galaxyproject/ansible-tiaas2/blob/6d9013776ecee21c042e9374e78ab83f4923eb18/tasks/main.yml#L74

Like:
```html
<!-- Use local Galaxy's stylesheet -->
<link rel="stylesheet" href="/static/dist/base.css">
```

**Comment by hexylena** [comment]
@natefoo  added that, I believe there's a good reason to keep it, if possible.
https://github.com/galaxyproject/ansible-tiaas2/commit/7bfc4b80044be75f33902b3aa1cc0cbe52e219cf (main does some odd things sometimes due to their setup.)
