### ISSUE TITLE
Gunicorn deployment not working

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/ansible-tiaas2#15]
After deploying with the gunicorn server I can't get the app to load. It seems like gunicorn can't find a request handler because it just loads until gunicorn's timeout limit is reached. In the browser I get `502 Bad Gateway`. In the logs I get this:

`journalctl -fu tiaas`:
```
Oct 17 04:40:31 dev systemd[1]: Started Training Infrastructure as a Service.
Oct 17 04:40:31 dev gunicorn[120054]: [2022-10-17 04:40:31 +0000] [120054] [INFO] Starting gunicorn 20.1.0
Oct 17 04:40:31 dev gunicorn[120054]: [2022-10-17 04:40:31 +0000] [120054] [INFO] Listening at: http://127.0.0.1:5000 (120054)
Oct 17 04:40:31 dev gunicorn[120054]: [2022-10-17 04:40:31 +0000] [120054] [INFO] Using worker: sync
Oct 17 04:40:31 dev gunicorn[120070]: [2022-10-17 04:40:31 +0000] [120070] [INFO] Booting worker with pid: 120070
Oct 17 04:41:08 dev gunicorn[120054]: [2022-10-17 04:41:08 +0000] [120054] [CRITICAL] WORKER TIMEOUT (pid:120070)
Oct 17 04:41:08 dev gunicorn[120070]: [2022-10-17 04:41:08 +0000] [120070] [INFO] Worker exiting (pid: 120070)
Oct 17 04:41:08 dev gunicorn[120075]: [2022-10-17 04:41:08 +0000] [120075] [INFO] Booting worker with pid: 120075
```

I can still run the development server from the CLI with `python manage.py runserver` so the app seems to be running ok.

<br>
<hr>
<br>

### A solution

I can fix this by setting up nginx/systemd to run gunicorn through a unix socket. This has a nice side effect that it will always start the tiaas service when a request comes in, if it's not already running. And it stops any confusion resolving `localhost` which might be causing the issue above?

```
# /etc/systemd/system/tiaas.socket

[Unit]
Description=Galaxy tiaas service socket
[Socket]
ListenStream=/run/tiaas.sock
[Install]
WantedBy=sockets.target
```

```
# /etc/systemd/system/tiaas.service

[Unit]
Description=Training Infrastructure as a Service
Documentation=https://github.com/usegalaxy-eu/tiaas2
Requires=tiaas.socket
After=network.target

[Service]
PIDFile=/run/gunicorn/pid
User=tiaas
Group=tiaas
RuntimeDirectory=gunicorn
WorkingDirectory=/opt/tiaas/code
Environment="PATH=/opt/tiaas/venv/bin:$PATH"
ExecStart=/opt/tiaas/venv/bin/gunicorn --bind unix:/run/tiaas.sock \
  --pid /run/gunicorn/pid   \
  --pythonpath '/opt/tiaas' \
  -c ../gunicorn.py \
  tiaas.wsgi
Restart=on-failure
RestartForceExitStatus=SIGPIPE
KillMode=control-group

[Install]
WantedBy=multi-user.target
```

```py
# /opt/tiaas/gunicorn.py

"""Add a worker for each available CPU.

Most requests are handled quickly, so 1 worker should generally be able to handle many
requests per second.
"""

workers = 1

# Environment variables
raw_env = [
    "DJANGO_SETTINGS_MODULE=tiaas.settings",
]
```

```
# /etc/nginx/sites-enabled/galaxy

...
    location /tiaas {
        proxy_pass            http://unix:/run/tiaas.sock;
        proxy_redirect        off;
        proxy_set_header      Host                 $host;
        proxy_set_header      X-Real-IP            $remote_addr;
        proxy_set_header      X-Forwarded-For      $proxy_add_x_forwarded_for;
        proxy_hide_header     X-Frame-Options;
        proxy_read_timeout    600;  # seconds
  }

    location /join-training {
        proxy_pass            http://unix:/run/tiaas.sock;
        proxy_redirect        off;
        proxy_set_header      Host                 $host;
        proxy_set_header      X-Real-IP            $remote_addr;
        proxy_set_header      X-Forwarded-For      $proxy_add_x_forwarded_for;
        proxy_hide_header     X-Frame-Options;
        proxy_read_timeout    600;  # seconds
    }
...
```

**Comment by hexylena** [comment]
This looks like a great solution, socket activation is a great choice here.

**Comment by hexylena** [comment]
Is `pidfile` necessary? We should be able to use a `notify` service based on the docs, https://docs.gunicorn.org/en/stable/deploy.html#systemd

Ah and we lose everything from `run.sh`, so we'll need to copy over the statsd bits I added.

**Comment by neoformit** [comment]
The `statsd` bit is actually there, it just didn't get templated as it's not defined in this playbook.
Yep, drop the PIDfile. Just a habit. I'll make a PR soon.

**Comment by neoformit** [comment]
What I still don't understand is the empty response when I curl the socket:
```
curl --unix-socket /run/tiaas.sock http://localhost/tiaas
```
In my other Django deployments this returns HTML :thinking: 

Also - what's the best way to role out the nginx conf update? Is there a way that these blocks could be templated by the tiaas role?

**Comment by hexylena** [comment]
```
$ curl --unix-socket /tmp/tiaas.sock http://localhost/tiaas -D -
HTTP/1.1 301 Moved Permanently
Server: gunicorn
Date: Tue, 18 Oct 2022 08:44:15 GMT
Connection: close
Content-Type: text/html; charset=utf-8
Location: /tiaas/
Content-Length: 0
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
```

LGTM ;) (add the `/`)

**Comment by hexylena** [comment]
> Also - what's the best way to role out the nginx conf update? Is there a way that these blocks could be templated by the tiaas role?

I've done that in the past, I'd support that again yea. Let's just have a `tiaas_nginx_routes` that we maintain, and for other uses, people can write/maintain their own.

**Comment by neoformit** [comment]
Yeah ok - so we'd define a default and that could be overwritten in group vars? Does that work when the default var is defined in the tiaas role and then templated by the Galaxy role? Still getting my head around some of the Ansible logic...

**Comment by hexylena** [comment]
yes, precisely! yes, it will still work then. the group værs version has higher precedence so when whichever role goes to read that, it will see the highest precedence version.

**Comment by neoformit** [comment]
Resolved with https://github.com/galaxyproject/ansible-tiaas2/pull/16
