### ISSUE TITLE
Ansible Role not Updated

### ISSUE THREAD

**Issue by BorisYourich** [galaxyproject/ansible-tiaas2#27]
The latest changes on github that would allow the admin to configure `TIAAS_SEND_EMAIL_FROM` are not available in the role galaxyproject.tiaas2 on Ansible Galaxy. I had to rewrite the `galaxyproject.tiaas2/templates/config.py`

**Comment by hexylena** [comment]
Hi @BorisYourich, we can definitely add a variable for this.

Otherwise you can always set additional variables which *don't* have a current default using `tiaas_other_config`, e.g. 

```
tiaas_other_config: |
  TIAAS_SEND_EMAL_FROM: user@host
```

so you shouldn't have to overwrite the `config.py` template ever :)

**Comment by hexylena** [comment]
Actually that was already in the role: https://github.com/galaxyproject/ansible-tiaas2/blob/main/templates/config.py#L8

it was added in
https://github.com/galaxyproject/ansible-tiaas2/commit/6ac1fbd94fe2ae28616d44165eecf8a332b66ab2

it was in tag `2.1.6` which is available, https://galaxy.ansible.com/ui/standalone/roles/galaxyproject/tiaas2/versions/

I'm not sure how we got a `2.2.0` which is older than our `2.1.6`, that looks like a bug.

I'll re-tag the main branch 2.2.1 to fix this.

**Comment by hexylena** [comment]
I'm having issues getting a new import going, ansible has changed

- how it accepts API keys (no longer on the CLI/env)
- the api keys I have both return 403 forbidden (@natefoo help)
- doing a manual import on ansible's website does not work.

In the meantime you can switch to `2.1.6` @BorisYourich

**Comment by BorisYourich** [comment]
> Hi @BorisYourich, we can definitely add a variable for this.
> 
> Otherwise you can always set additional variables which _don't_ have a current default using `tiaas_other_config`, e.g.
> 
> ```
> tiaas_other_config: |
>   TIAAS_SEND_EMAL_FROM: user@host
> ```
> 
> so you shouldn't have to overwrite the `config.py` template ever :)

Slick! I didn't realize that is an option, Thank you !
Also for the ansible role version, I will probably wait for the new one and use the other_config for now.
