### ISSUE TITLE
Local config file may have wrong permissions

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/ansible-tiaas2#3]
Shouldn't [the mode for `local_settings.py`](https://github.com/usegalaxy-eu/ansible-tiaas2/blob/master/tasks/main.yml#L70) be `0644` instead? I don't think that file should be executable.

**Comment by hexylena** [comment]
Yep, doesn't *need* to be executable (but also doesn't affect/hurt anything.) 0640 would be better since there is sensitive information in there though!

**Comment by jdavcs** [comment]
Done!
